#!/usr/bin/env bash
set -euo pipefail

out="${1:-artifacts/ai_sweep/latest}"

cargo run --locked -- ai-sweep --out "$out"
python3 -m json.tool "$out/ai_sweep.json" >/dev/null
grep -q '"schema": "oathyard.ai_sweep.v1"' "$out/ai_sweep.json"
grep -q '"runs_per_pairing": 2' "$out/ai_sweep.json"
grep -q '"pairing_count": 6' "$out/ai_sweep.json"
grep -q '"total_contacts": 37' "$out/ai_sweep.json"
grep -q '"capability_reaction_count": 58' "$out/ai_sweep.json"
grep -q '"distinct_action_labels": 11' "$out/ai_sweep.json"
grep -q '"policy_style_count": 6' "$out/ai_sweep.json"
grep -q '"unique_final_hashes": 6' "$out/ai_sweep.json"
grep -q '"all_pairings_stable": true' "$out/ai_sweep.json"
grep -q '"all_replays_verified": true' "$out/ai_sweep.json"
grep -q '"all_actions_legal": true' "$out/ai_sweep.json"
grep -q '"all_truth_actions_valid": true' "$out/ai_sweep.json"
grep -q '"difficulty_changes_body_stats": false' "$out/ai_sweep.json"
grep -q '"body_stat_mutation_by_ai": false' "$out/ai_sweep.json"
grep -q '"outcome_authority": "truth_replay_only"' "$out/ai_sweep.json"
grep -q '"id": "reach_vs_mail"' "$out/ai_sweep.json"
grep -q '"id": "hook_vs_plate"' "$out/ai_sweep.json"
grep -q '"id": "maul_vs_fencer"' "$out/ai_sweep.json"
grep -q '"id": "curve_vs_spear_lamellar"' "$out/ai_sweep.json"
grep -q '"id": "shield_counter_vs_curve"' "$out/ai_sweep.json"
grep -q '"id": "spear_vs_maul_pressure"' "$out/ai_sweep.json"
grep -q '"policy_0": "guard_counter"' "$out/ai_sweep.json"
grep -q '"policy_1": "reach_pressure"' "$out/ai_sweep.json"
grep -q '"policy_0": "bind_control"' "$out/ai_sweep.json"
grep -q '"policy_0": "heavy_pressure"' "$out/ai_sweep.json"
grep -q '"policy_1": "evasive_counter"' "$out/ai_sweep.json"
grep -q '"policy_0": "low_line_disruptor"' "$out/ai_sweep.json"
grep -q '"stable_committed_sequences": true' "$out/ai_sweep.json"
grep -q '"stable_replay": true' "$out/ai_sweep.json"
grep -q '"stable_trace": true' "$out/ai_sweep.json"
grep -q '"action": "recover"' "$out/ai_sweep.json"
grep -q '"action": "guard"' "$out/ai_sweep.json"
grep -q '"action": "parry"' "$out/ai_sweep.json"
grep -q '"action": "thrust"' "$out/ai_sweep.json"
grep -q '"action": "shove"' "$out/ai_sweep.json"
grep -q '"action": "kick"' "$out/ai_sweep.json"
grep -q 'Status: PASSED' "$out/ai_sweep_report.md"
grep -q '## Action Coverage' "$out/ai_sweep_report.md"
grep -q '## Policy Styles' "$out/ai_sweep_report.md"
