#!/usr/bin/env python3
"""Unit-103: Contact sheet + markdown generation for roster asset capture matrix.

Reads the matrix JSON produced by `oathyard play --capture-roster-matrix <dir>`,
generates:
  - asset_matrix_contact_sheet.png  (all 22 assets)
  - fighters_contact_sheet.png
  - weapons_contact_sheet.png
  - armor_contact_sheet.png
  - arenas_contact_sheet.png
  - roster_asset_capture_matrix.md
  - visual_scores.md

Uses PIL (Pillow) for image composition — no fabrication, just visual layout.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    print("ERROR: PIL/Pillow not available for contact sheet generation", file=sys.stderr)
    sys.exit(1)


def load_matrix(matrix_dir: Path) -> dict:
    matrix_path = matrix_dir / "roster_asset_capture_matrix.json"
    if not matrix_path.exists():
        print(f"ERROR: matrix JSON not found at {matrix_path}", file=sys.stderr)
        sys.exit(1)
    return json.loads(matrix_path.read_text())


def make_contact_sheet(
    assets: list[dict],
    matrix_dir: Path,
    output_name: str,
    title: str,
    cols: int = 4,
    thumb_w: int = 480,
    thumb_h: int = 270,
) -> Path:
    """Create a contact sheet PNG from a list of asset entries."""
    rows = (len(assets) + cols - 1) // cols
    label_h = 30
    cell_w = thumb_w
    cell_h = thumb_h + label_h
    padding = 10
    title_h = 50

    canvas_w = cols * cell_w + (cols + 1) * padding
    canvas_h = rows * cell_h + (rows + 1) * padding + title_h

    canvas = Image.new("RGB", (canvas_w, canvas_h), (20, 20, 24))
    draw = ImageDraw.Draw(canvas)

    try:
        font_title = ImageFont.truetype(
            "/usr/share/fonts/liberation-sans/LiberationSans-Bold.ttf", 24
        )
        font_label = ImageFont.truetype(
            "/usr/share/fonts/liberation-sans/LiberationSans-Regular.ttf", 14
        )
    except (OSError, IOError):
        font_title = ImageFont.load_default()
        font_label = ImageFont.load_default()

    draw.text((padding, 10), title, fill=(255, 255, 255), font=font_title)

    for idx, asset in enumerate(assets):
        col = idx % cols
        row = idx // cols
        x = padding + col * (cell_w + padding)
        y = title_h + padding + row * (cell_h + padding)

        asset_id = asset["asset_id"]
        kind = asset["kind"]
        status = asset.get("visual_status", "unknown")

        screenshot_path = matrix_dir / asset.get("screenshot_path", "")
        if screenshot_path.exists():
            try:
                img = Image.open(screenshot_path).convert("RGB")
                img.thumbnail((thumb_w, thumb_h), Image.Resampling.LANCZOS)
                paste_x = x + (cell_w - img.width) // 2
                paste_y = y + (thumb_h - img.height) // 2
                canvas.paste(img, (paste_x, paste_y))
            except Exception as e:
                draw.text(
                    (x + 10, y + thumb_h // 2),
                    f"IMG ERROR: {e}",
                    fill=(255, 0, 0),
                    font=font_label,
                )
        else:
            draw.rectangle([x, y, x + thumb_w, y + thumb_h], fill=(40, 20, 20))
            draw.text(
                (x + 10, y + thumb_h // 2),
                f"NO SCREENSHOT",
                fill=(255, 80, 80),
                font=font_label,
            )

        # Status color
        status_color = {"pass": (80, 255, 80), "warn": (255, 200, 80), "fail": (255, 80, 80)}.get(
            status, (200, 200, 200)
        )
        draw.rectangle([x, y + thumb_h, x + cell_w, y + cell_h], fill=(30, 30, 36))
        draw.text((x + 5, y + thumb_h + 5), f"{asset_id}", fill=(255, 255, 255), font=font_label)
        draw.text(
            (x + cell_w - 60, y + thumb_h + 5),
            f"[{status}]",
            fill=status_color,
            font=font_label,
        )

    output_path = matrix_dir / output_name
    canvas.save(str(output_path), "PNG")
    return output_path


def generate_markdown(matrix: dict, matrix_dir: Path, sheets: dict[str, Path]) -> None:
    md_path = matrix_dir / "roster_asset_capture_matrix.md"
    lines = [
        "# OATHYARD Roster Asset Capture Matrix (Unit-103)",
        "",
        f"**Schema**: `{matrix.get('schema', 'unknown')}`",
        f"**Generated by executable**: `{matrix.get('generated_by_executable', False)}`",
        f"**Command**: `{matrix.get('executable_command', 'N/A')}`",
        f"**Package-relative paths only**: `{matrix.get('package_relative_paths_only', True)}`",
        "",
        "## Readiness Boundary",
        "",
        f"- `truth_mutation`: **{matrix.get('truth_mutation', 'N/A')}**",
        f"- `production_asset_ready`: **{matrix.get('production_asset_ready', 'N/A')}**",
        f"- `owner_visual_accepted`: **{matrix.get('owner_visual_accepted', 'N/A')}**",
        f"- `public_demo_ready`: **{matrix.get('public_demo_ready', 'N/A')}**",
        f"- `release_candidate_ready`: **{matrix.get('release_candidate_ready', 'N/A')}**",
        "",
        "## Asset Counts",
        "",
        f"- Total: **{matrix.get('asset_count_total', 'N/A')}**",
    ]
    kc = matrix.get("kind_counts", {})
    for kind in ["fighter", "weapon", "armor", "arena"]:
        lines.append(f"  - {kind}: **{kc.get(kind, 'N/A')}**")

    summary = matrix.get("capture_summary", {})
    lines.extend(
        [
            "",
            "## Capture Summary",
            "",
            f"- Captured: **{summary.get('captured', 'N/A')}**",
            f"- Failed: **{summary.get('failed', 'N/A')}**",
            f"- Resolution: **{matrix.get('capture_resolution', 'N/A')}**",
            f"- Backend: `{matrix.get('renderer_backend', 'N/A')}`",
            "",
            "## Contact Sheets",
            "",
        ]
    )
    for name, path in sheets.items():
        lines.append(f"- **{name}**: `{path.name}`")

    lines.extend(["", "## Per-Asset Details", "", "| Asset ID | Kind | Status | Vertices | Triangles | Mesh Consumed | Texture Bound | SHA256 |", "|---|---|---|---|---|---|---|---|"])

    for asset in matrix.get("assets", []):
        sha = asset.get("screenshot_sha256", "")
        sha_short = sha[:16] + "..." if len(sha) > 16 else sha
        lines.append(
            f"| {asset['asset_id']} | {asset['kind']} | **{asset.get('visual_status', '?')}** | "
            f"{asset.get('vertex_count', '?')} | {asset.get('triangle_count', '?')} | "
            f"{asset.get('mesh_geometry_consumed', '?')} | "
            f"{asset.get('material_texture_binding', '?')} | `{sha_short}` |"
        )

    md_path.write_text("\n".join(lines) + "\n")


def generate_scores_md(matrix_dir: Path) -> None:
    scores_path = matrix_dir / "visual_scores.json"
    md_path = matrix_dir / "visual_scores.md"
    if not scores_path.exists():
        return
    scores = json.loads(scores_path.read_text())
    lines = [
        "# Visual Scores (Unit-103)",
        "",
        f"Asset count: **{scores.get('asset_count', 'N/A')}**",
        "",
        "| Asset ID | Kind | Status | Vertices | Triangles | Geometry | Material | Notes |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for s in scores.get("scores", []):
        lines.append(
            f"| {s['asset_id']} | {s['kind']} | **{s['visual_status']}** | "
            f"{s.get('vertex_count', '?')} | {s.get('triangle_count', '?')} | "
            f"{s.get('mesh_geometry_consumed', '?')} | "
            f"{s.get('material_texture_binding', '?')} | {s.get('notes', '')} |"
        )
    md_path.write_text("\n".join(lines) + "\n")


def main() -> None:
    if len(sys.argv) < 2:
        print("usage: generate_contact_sheets.py <matrix_dir>", file=sys.stderr)
        sys.exit(1)
    matrix_dir = Path(sys.argv[1])
    matrix = load_matrix(matrix_dir)
    assets = matrix.get("assets", [])

    sheets: dict[str, Path] = {}

    # Full contact sheet.
    sheets["All Assets"] = make_contact_sheet(
        assets, matrix_dir, "asset_matrix_contact_sheet.png", "OATHYARD Roster Asset Capture Matrix — All 22 Assets"
    )

    # Per-kind sheets.
    for kind in ["fighter", "weapon", "armor", "arena"]:
        kind_assets = [a for a in assets if a["kind"] == kind]
        if kind_assets:
            plural = {"fighter": "Fighters", "weapon": "Weapons", "armor": "Armor", "arena": "Arenas"}[kind]
            sheets[plural] = make_contact_sheet(
                kind_assets,
                matrix_dir,
                f"{kind}s_contact_sheet.png",
                f"OATHYARD {plural} ({len(kind_assets)} assets)",
                cols=min(len(kind_assets), 4),
            )

    generate_markdown(matrix, matrix_dir, sheets)
    generate_scores_md(matrix_dir)

    print(f"Contact sheets generated in {matrix_dir}")
    for name, path in sheets.items():
        print(f"  {name}: {path.name}")


if __name__ == "__main__":
    main()
